apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-nginx
  name: deploy-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-nginx
    spec:
      containers:
      - image: jlsshrn8621001/myprivate
        name: nginx
        resources:  
          requests:
            cpu: 200m
          limits:
            cpu: 500m
        ports:
        - containerPort: 30000
        resources: {}
      imagePullSecrets:
        - name: sample-docker-secret
      
status: {}
