apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: volume-demo
  name: volume-demo
spec:
  containers:
  - image: nginx
    name: volume-demo
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html #mout the volume nginx-storage inside the container with this path   
      name: nginx-storage #have to much with the vomlume name  
  volumes:
  - name: nginx-storage
    emptyDir: {}
  restartPolicy: Always
status: {}
