apiVersion: v1
kind: Service
metadata:
  name: my-ns
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx #select the pods that ahve this label
  type: NodePort
status:
  loadBalancer: {}
